# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 140b818b0b03afc671fb693a13541b3701536dd068d258acdcdebea731a6f54f2b4305d4b85b1b372f46056f4dbcb87cc8903c27ab8258bd6146eb8e1466a2a6

test:
  secret_key_base: 3703775dbef5679877ef1789654602431c47dcb61fdb38939fb4e512fa9c94e9e7264d30baadf8a8a42da5b8ffabc84e11585ebb4c7277c0e2a82b5429ac91cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
